In [5]:
import numpy as np

# 创建一个一维数组
a = np.array([0, 1, 2, 3, 4, 5])
# 创建一个二维数组
b = np.array(
    [
        [11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25],
        [31, 32, 33, 34, 35],
        [41, 42, 43, 44, 45],
        [41, 42, 43, 44, 45],
    ]
)

print("a 的维数：", a.ndim)
print("a 的元素数量：", a.size)
print("a 的形状：", a.shape)


print("b 的维数：", b.ndim)
print("b 的元素数量：", b.size)
print("b 的形状：", b.shape)

a 的维数： 1
a 的元素数量： 6
a 的形状： (6,)
b 的维数： 2
b 的元素数量： 25
b 的形状： (5, 5)


In [3]:
print(np.zeros((3, 4))) # 创建一个形状 3 x 4 所有元素都为 0 的数组
print(np.ones( (2, 3), dtype=np.int16 )) # 创建一个形状 2 x 3
                                         # 所有元素都为 1
                                         # 类型为 int16 的数组
print(np.empty((4, 35))) # 创始数组时不进行初始化，里面的元素可能为任何值

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[            nan 0.00000000e+000 1.42349984e-311 1.42349797e-311
  0.00000000e+000             nan             nan 0.00000000e+000
  4.94065646e-324 0.00000000e+000 4.44659081e-323 1.42349984e-311
  1.42349797e-311 0.00000000e+000 0.00000000e+000             nan
  0.00000000e+000 4.94065646e-324 3.55727265e-322 5.43472210e-323
  1.42349984e-311 1.42349797e-311 2.47032823e-323 1.38338381e-322
              nan 0.00000000e+000 4.94065646e-324 7.11454530e-322
  5.43472210e-323 1.42349984e-311 1.42349797e-311             nan
  1.48219694e-322             nan 0.00000000e+000]
 [4.94065646e-324 1.06718180e-321 5.43472210e-323 1.42349984e-311
  1.42349797e-311 0.00000000e+000 1.28457068e-322             nan
  0.00000000e+000 4.94065646e-324 1.42290906e-321 5.43472210e-323
  1.42349984e-311 1.42349797e-311 0.00000000e+000 7.90505033e-323
              nan 0.00000000e+000 4.94065646e-324 0.00000000e+000
  0.00000000e+000 0.000000

In [16]:
# 针对一维数组切片
print(a[2:4])
print(a[2:])
print(a[:4])
print(a[:])
print(a[::2])

[2 3]
[2 3 4]
[0 1 2 3]
[0 1 2 3 4]
[0 2 4]


In [17]:
# 针对二维数组切片
print(b[:2])
print(b[2:4, 2:4])
print(b[:, 2:4])
print(b[:, 2])

[[11 12 13 14 15]
 [21 22 23 24 25]]
[[33 34]
 [43 44]]
[[13 14]
 [23 24]
 [33 34]
 [43 44]
 [43 44]]
[13 23 33 43 43]


In [7]:
print(a.reshape(2, 3))

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [9]:
print(b.ravel())

[11 12 13 14 15 21 22 23 24 25 31 32 33 34 35 41 42 43 44 45 41 42 43 44
 45]


In [10]:
print(b.reshape(-1))

[11 12 13 14 15 21 22 23 24 25 31 32 33 34 35 41 42 43 44 45 41 42 43 44
 45]
